main/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [path('admin/', admin.site.urls), path('tasks/', include('tasks.urls'))]

tasks/urls.py
from django.urls import path

from . import views

app_name = 'tasks'

urlpatterns = [
    #'loquesea/'
    path('', views.task_list, name='task-list'),
    path('add/', views.add_task, name='add-task'),
    path('completed/', views.task_list_completed, name='task-list-completed'),
    path('pending/', views.task_list_pending, name='task-list-pending'),
    path('<slug:task_slug>/edit/', views.edit_task, name='edit-task'),
    path('<slug:task_slug>/delete/', views.delete_task, name='delete-task'),
    path('<slug:task_slug>/toggle/', views.toggle_task, name='toggle-task'),
    path('<slug:task_slug>/', views.task_detail, name='task-detail'),
]

shared/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models


class Task(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField(blank=True)
    slug = models.SlugField(unique=True)
    completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

tasks/forms.py
from django import forms

from .models import Task


class EditTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('name', 'description')


class AddTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('name', 'description')

shared/views.py
from django.shortcuts import render

# Create your views here.

tasks/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.utils.text import slugify

from .forms import AddTaskForm, EditTaskForm
from .models import Task


def task_list(request):
    tasks = Task.objects.all()

    return render(request, 'tasks/task/list.html', {'tasks': tasks})


def task_detail(request, task_slug: str):
    try:
        task = Task.objects.get(slug=task_slug)
    except Task.DoesNotExist:
        return HttpResponse(f'La tarea "{task_slug}" no existe')
    return render(request, 'tasks/task/detail.html', {'task': task})


def task_list_pending(request):
    tasks = Task.objects.filter(completed=False)

    return render(request, 'tasks/task/list_pending.html', {'tasks': tasks})


def task_list_completed(request):
    tasks = Task.objects.filter(completed=True)

    return render(request, 'tasks/task/list_completed.html', {'tasks': tasks})


def edit_task(request, task_slug: str):
    task = Task.objects.get(slug=task_slug)
    if request.method == 'POST':
        if (form := EditTaskForm(request.POST, instance=task)).is_valid():
            task = form.save(commit=False)
            task.slug = slugify(task.name)
            task.save()
            return redirect('tasks:task-detail', task_slug=task.slug)
    else:
        form = EditTaskForm(instance=task)
    return render(request, 'tasks/task/edit.html', dict(task=task, form=form))


def delete_task(request, task_slug: str):
    Task.objects.get(slug=task_slug).delete()
    return redirect('tasks:task-list')


def add_task(request):
    if request.method == 'POST':
        if (form := AddTaskForm(request.POST)).is_valid():  # Crea objeto AddTaskform
            task = form.save(commit=False)
            task.slug = slugify(task.name)  # slugifea el titulo
            task.save()  # Guarda en baase de datos
            return redirect('tasks:task-list')  # TE lleva a task/tasks/list
    else:
        form = AddTaskForm()
    return render(request, 'tasks/task/add.html', dict(form=form))


def toggle_task(request, task_slug):
    task = Task.objects.get(slug=task_slug)
    task.completed = not task.completed
    task.save()
    return redirect('tasks:task-list')

shared/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>SuperTODO</title>
  </head>

  <body>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
  </body>
</html>

shared/templates/header.html
<div class="header">
    <h1>SuperTODO</h1>
    <h2>{{ subtitle }}</h1>
</div>

shared/templates/links.html
<div class="links">
    <a href="{% url 'tasks:task-list' %}">Todas las tareas</a>
    <a href="{% url 'tasks:task-list-completed' %}">Tareas completadas</a>
    <a href="{% url 'tasks:task-list-pending' %}">Tareas pendientes</a>
    <a href="{% url 'tasks:add-task' %}">Añadir tarea</a>
</div>

tasks/templates/tasks/list_pending.html
{% block content%}

{% include "header.html" %}

<ul>
  {% for task in tasks %}
  <li>{{task.name}}</li>
  {% endfor %}




</ul>



{% endblock %}

tasks/templates/tasks/task/add.html
<form method="post">
{% include "header.html" with subtitle="Añadir tarea"%}
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Crear tarea">

</form>
<a href="{% url 'tasks:task-list' %}">Cancelar</a>

tasks/templates/tasks/task/detail.html
{% block content %}

{% include "header.html" %}
<p>{{ task.name }}</p>
<p>{% if task.completed %}
  Completada
  {% else %}
  Pendiente
  {% endif %}</p>
<p>{{ task.description }}</p>

<a href="{% url 'tasks:task-list' %}">Volver</a>

{% endblock %}

tasks/templates/tasks/task/edit.html
{% include "header.html" with subtitle="Editar tarea"%}

<form method="post" novalidate>
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Guardar">
</form>

<a href="{% url 'tasks:task-list' %}">Cancelar</a>

tasks/templates/tasks/task/list.html
{% block content %}


{% include "header.html" with subtitle="Todas las tareas"%}

{% for task in tasks %}

<p>{{ task.name }} 
  {% if task.completed %} ✅ 
  {% else %} ❌ 
  {% endif %}
  <a href="{% url 'tasks:task-detail' task.slug %}"> Más información</a>
  <a href="{% url 'tasks:toggle-task' task.slug %}"> Cambiar estado</a>
  <a href="{% url 'tasks:edit-task' task.slug %}">Editar tarea</a>
  <a href="{% url 'tasks:delete-task' task.slug %}">Borrar tarea</a>
</p>

  {% empty %}
  <p>Nada que hacer. ¡Enhorabuena!</p>
{% endfor %}

{% include "links.html" %}

{% endblock %}

tasks/templates/tasks/task/list_completed.html
{% block content%}

{% include "header.html" with subtitle="Tareas completadas" %}

<ul>
  {% for task in tasks %}
  <li>{{task.name}}
    {% if task.completed %} ✅ 
    {% else %} ❌ 
    {% endif %}
    <a href="{% url 'tasks:task-detail' task.slug %}"> Más información</a>
    <a href="{% url 'tasks:toggle-task' task.slug %}"> Cambiar estado</a>
    <a href="{% url 'tasks:edit-task' task.slug %}">Editar tarea</a>
    <a href="{% url 'tasks:delete-task' task.slug %}">Borrar tarea</a>
  </li>
    {% empty %}
  <p>Nada que hacer. ¡Enhorabuena!</p>
  {% endfor %}
</ul>

{% include "links.html" %}

{% endblock %}

tasks/templates/tasks/task/list_pending.html
{% block content%}

{% include "header.html" with subtitle="Tareas pendientes" %}

<ul>
  {% for task in tasks %}
  <li>{{task.name}}
    {% if task.completed %} ✅ 
    {% else %} ❌ 
    {% endif %}
    <a href="{% url 'tasks:task-detail' task.slug %}"> Más información</a>
    <a href="{% url 'tasks:toggle-task' task.slug %}"> Cambiar estado</a>
    <a href="{% url 'tasks:edit-task' task.slug %}">Editar tarea</a>
    <a href="{% url 'tasks:delete-task' task.slug %}">Borrar tarea</a>
  </li>
    {% empty %}
  <p>Nada que hacer. ¡Enhorabuena!</p>
  {% endfor %}
</ul>

{% include "links.html" %}

{% endblock %}

tasks/templates/tasks/task/specific_list.html
{% block content%}

{% include "header.html" with subtitle="Tareas pendientes" %}

<ul>
  {% for task in tasks %}
  <li>{{task.name}}
    {% if task.completed %} ✅ 
    {% else %} ❌ 
    {% endif %}
    <a href="{% url 'tasks:task-detail' task.slug %}"> Más información</a>
    <a href="{% url 'tasks:toggle-task' task.slug %}"> Cambiar estado</a>
    <a href="{% url 'tasks:edit-task' task.slug %}">Editar tarea</a>
    <a href="{% url 'tasks:delete-task' task.slug %}">Borrar tarea</a>
  </li>
    {% empty %}
  <p>Nada que hacer. ¡Enhorabuena!</p>
  {% endfor %}
</ul>

{% include "links.html" %}

{% endblock %}